[unix_http_server]
file=/tmp/supervisor/supervisord.sock  ; the path to the socket file
[supervisord]
logfile=/tmp/supervisor/supervisord.log ; main log file; default $CWD/supervisord.log
pidfile=/tmp/supervisor/supervisord.pid ; supervisord pidfile; default supervisord.pid
nodaemon=true                          ; start in foreground if true; default false
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=unix:///tmp/supervisor/supervisord.sock ; use a unix:// URL for a unix socket
[include]
files = /etc/supervisor.d/*.ini