export const duoToneListIcons = [
  { name: 'adhesive-plaster-2', icon: 'svgo-duo-adhesive-plaster-2' },
  { name: 'adhesive-plaster', icon: 'svgo-duo-adhesive-plaster' },
  { name: 'airbuds-case', icon: 'svgo-duo-airbuds-case' },
  { name: 'airbuds', icon: 'svgo-duo-airbuds' },
  { name: 'alarm', icon: 'svgo-duo-alarm' },
  { name: 'album', icon: 'svgo-duo-album' },
  { name: 'archive', icon: 'svgo-duo-archive-up-minimlistic' },
  { name: 'archive', icon: 'svgo-duo-archive' },
  { name: 'armchair-2', icon: 'svgo-duo-armchair-2' },
  { name: 'armchair', icon: 'svgo-duo-armchair' },
  { name: 'asteroid', icon: 'svgo-duo-asteroid' },
  { name: 'atom', icon: 'svgo-duo-atom' },
  { name: 'backpack', icon: 'svgo-duo-backpack' },
  { name: 'bacteria', icon: 'svgo-duo-bacteria' },
  { name: 'bag-2', icon: 'svgo-duo-bag-2' },
  { name: 'bag-3', icon: 'svgo-duo-bag-3' },
  { name: 'bag-4', icon: 'svgo-duo-bag-4' },
  { name: 'bag-5', icon: 'svgo-duo-bag-5' },
  { name: 'bag-heart', icon: 'svgo-duo-bag-heart' },
  { name: 'bag', icon: 'svgo-duo-bag' },
  { name: 'balloon', icon: 'svgo-duo-balloon' },
  { name: 'balls', icon: 'svgo-duo-balls' },
  { name: 'bank note banknote 2', icon: 'svgo-duo-banknote-2' },
  { name: 'banknote', icon: 'svgo-duo-banknote' },
  { name: 'bar-chair', icon: 'svgo-duo-bar-chair' },
  { name: 'basketball', icon: 'svgo-duo-basketball' },
  { name: 'bath', icon: 'svgo-duo-bath' },
  { name: 'battery-charge', icon: 'svgo-duo-battery-charge' },
  { name: 'bed', icon: 'svgo-duo-bed' },
  { name: 'bedside table 2', icon: 'svgo-duo-bedside-table-2' },
  { name: 'bedside table 3', icon: 'svgo-duo-bedside-table-3' },
  { name: 'bedside table 4', icon: 'svgo-duo-bedside-table-4' },
  { name: 'bedside table', icon: 'svgo-duo-bedside-table' },
  { name: 'body', icon: 'svgo-duo-body' },
  { name: 'bolt', icon: 'svgo-duo-bolt-circle' },
  { name: 'bone', icon: 'svgo-duo-bone' },
  { name: 'bonfire', icon: 'svgo-duo-bonfire' },
  { name: 'book bookmark', icon: 'svgo-duo-book-bookmark-minimalistic' },
  { name: 'bookmark-square', icon: 'svgo-duo-bookmark-square' },
  { name: 'bottle', icon: 'svgo-duo-bottle' },
  { name: 'bowling', icon: 'svgo-duo-bowling' },
  { name: 'box', icon: 'svgo-duo-box' },
  { name: 'calculator', icon: 'svgo-duo-calculator' },
  { name: 'calendar-add', icon: 'svgo-duo-calendar-add' },
  { name: 'calendar', icon: 'svgo-duo-calendar' },
  { name: 'camera-minimalistic', icon: 'svgo-duo-camera-minimalistic' },
  { name: 'camera', icon: 'svgo-duo-camera' },
  { name: 'card-2', icon: 'svgo-duo-card-2' },
  { name: 'card-recive', icon: 'svgo-duo-card-recive' },
  { name: 'card-search', icon: 'svgo-duo-card-search' },
  { name: 'card-send', icon: 'svgo-duo-card-send' },
  { name: 'card-transfer', icon: 'svgo-duo-card-transfer' },
  { name: 'card', icon: 'svgo-duo-card' },
  { name: 'cardholder', icon: 'svgo-duo-cardholder' },
  { name: 'cart-3', icon: 'svgo-duo-cart-3' },
  { name: 'cart-check', icon: 'svgo-duo-cart-check' },
  { name: 'cart', icon: 'svgo-duo-cart' },
  { name: 'case-minimalistic', icon: 'svgo-duo-case-minimalistic' },
  { name: 'case-round', icon: 'svgo-duo-case-round' },
  { name: 'cash-out', icon: 'svgo-duo-cash-out' },
  { name: 'cassette-2', icon: 'svgo-duo-cassette-2' },
  { name: 'chair-2', icon: 'svgo-duo-chair-2' },
  { name: 'chair', icon: 'svgo-duo-chair' },
  { name: 'chandelier', icon: 'svgo-duo-chandelier' },
  { name: 'chart-2', icon: 'svgo-duo-chart-2' },
  { name: 'chat-square-call', icon: 'svgo-duo-chat-square-call' },
  { name: 'chat-square-like', icon: 'svgo-duo-chat-square-like' },
  { name: 'chat-square', icon: 'svgo-duo-chat-square' },
  { name: 'chef-hat-heart', icon: 'svgo-duo-chef-hat-heart' },
  { name: 'chef-hat-minimalistic', icon: 'svgo-duo-chef-hat-minimalistic' },
  { name: 'clapperboard-edit', icon: 'svgo-duo-clapperboard-edit' },
  { name: 'clapperboard-open-play', icon: 'svgo-duo-clapperboard-open-play' },
  { name: 'clapperboard-text', icon: 'svgo-duo-clapperboard-text' },
  { name: 'clipboard-heart', icon: 'svgo-duo-clipboard-heart' },
  { name: 'clipboard-list', icon: 'svgo-duo-clipboard-list' },
  { name: 'closet-2', icon: 'svgo-duo-closet-2' },
  { name: 'closet', icon: 'svgo-duo-closet' },
  { name: 'cloud-bolt-minimalistic', icon: 'svgo-duo-cloud-bolt-minimalistic' },
  { name: 'cloud-rain', icon: 'svgo-duo-cloud-rain' },
  { name: 'code', icon: 'svgo-duo-code' },
  { name: 'colour-tuneing', icon: 'svgo-duo-colour-tuneing' },
  { name: 'condicioner', icon: 'svgo-duo-condicioner' },
  { name: 'confetti-minimalistic', icon: 'svgo-duo-confetti-minimalistic' },
  { name: 'corkscrew', icon: 'svgo-duo-corkscrew' },
  { name: 'cosmetic', icon: 'svgo-duo-cosmetic' },
  { name: 'cpu', icon: 'svgo-duo-cpu' },
  { name: 'crown-line', icon: 'svgo-duo-crown-line' },
  { name: 'cup-first', icon: 'svgo-duo-cup-first' },
  { name: 'cup-hot', icon: 'svgo-duo-cup-hot' },
  { name: 'cup-paper', icon: 'svgo-duo-cup-paper' },
  { name: 'cup', icon: 'svgo-duo-cup' },
  { name: 'database', icon: 'svgo-duo-database' },
  { name: 'delivery', icon: 'svgo-duo-delivery' },
  { name: 'devices', icon: 'svgo-duo-devices' },
  { name: 'diagram-down', icon: 'svgo-duo-diagram-down' },
  { name: 'diploma', icon: 'svgo-duo-diploma' },
  { name: 'diskette', icon: 'svgo-duo-diskette' },
  { name: 'display', icon: 'svgo-duo-display' },
  { name: 'dna', icon: 'svgo-duo-dna' },
  { name: 'document-add', icon: 'svgo-duo-document-add' },
  { name: 'documents-minimalistic', icon: 'svgo-duo-documents-minimalistic' },
  { name: 'dollar', icon: 'svgo-duo-dollar' },
  { name: 'donut-bitten', icon: 'svgo-duo-donut-bitten' },
  { name: 'dumbbell-large', icon: 'svgo-duo-dumbbell-large' },
  { name: 'dumbbell-small', icon: 'svgo-duo-dumbbell-small' },
  { name: 'earth', icon: 'svgo-duo-earth' },
  { name: 'emoji-funny-square', icon: 'svgo-duo-emoji-funny-square' },
  { name: 'end-call-rounded', icon: 'svgo-duo-end-call-rounded' },
  { name: 'eraser', icon: 'svgo-duo-eraser' },
  { name: 'euro', icon: 'svgo-duo-euro' },
  { name: 'eye', icon: 'svgo-duo-eye' },
  { name: 'face-scan-square', icon: 'svgo-duo-face-scan-square' },
  { name: 'filter', icon: 'svgo-duo-filter' },
  { name: 'fire', icon: 'svgo-duo-fire' },
  { name: 'flag', icon: 'svgo-duo-flag' },
  { name: 'flame', icon: 'svgo-duo-flame' },
  { name: 'flash-drive', icon: 'svgo-duo-flash-drive' },
  { name: 'flashlight-on', icon: 'svgo-duo-flashlight-on' },
  { name: 'floor-lamp-minimalistic', icon: 'svgo-duo-floor-lamp-minimalistic' },
  { name: 'floor-lamp', icon: 'svgo-duo-floor-lamp' },
  { name: 'football', icon: 'svgo-duo-football' },
  { name: 'fridge', icon: 'svgo-duo-fridge' },
  { name: 'fuel', icon: 'svgo-duo-fuel' },
  { name: 'gallery-edit', icon: 'svgo-duo-gallery-edit' },
  { name: 'gameboy', icon: 'svgo-duo-gameboy' },
  { name: 'gamepad-charge', icon: 'svgo-duo-gamepad-charge' },
  { name: 'ghost-smile', icon: 'svgo-duo-ghost-smile' },
  { name: 'gift', icon: 'svgo-duo-gift' },
  { name: 'glasses', icon: 'svgo-duo-glasses' },
  { name: 'global', icon: 'svgo-duo-global' },
  { name: 'globus', icon: 'svgo-duo-globus' },
  { name: 'golf', icon: 'svgo-duo-golf' },
  { name: 'gps', icon: 'svgo-duo-gps' },
  { name: 'hanger-2', icon: 'svgo-duo-hanger-2' },
  { name: 'hanger', icon: 'svgo-duo-hanger' },
  { name: 'headphones-round-sound', icon: 'svgo-duo-headphones-round-sound' },
  { name: 'headphones-square', icon: 'svgo-duo-headphones-square' },
  { name: 'health', icon: 'svgo-duo-health' },
  { name: 'heart', icon: 'svgo-duo-heart' },
  { name: 'hiking', icon: 'svgo-duo-hiking' },
  { name: 'history-3', icon: 'svgo-duo-history-3' },
  { name: 'home-angle-2', icon: 'svgo-duo-home-angle-2' },
  { name: 'hourglass-line', icon: 'svgo-duo-hourglass-line' },
  { name: 'inbox-archive', icon: 'svgo-duo-inbox-archive' },
  { name: 'inbox-in', icon: 'svgo-duo-inbox-in' },
  { name: 'incognito', icon: 'svgo-duo-incognito' },
  { name: 'iphone', icon: 'svgo-duo-iphone' },
  { name: 'jar-of-pills-2', icon: 'svgo-duo-jar-of-pills-2' },
  { name: 'jar-of-pills', icon: 'svgo-duo-jar-of-pills' },
  { name: 'key', icon: 'svgo-duo-key' },
  { name: 'keyboard', icon: 'svgo-duo-keyboard' },
  { name: 'ladle', icon: 'svgo-duo-ladle' },
  { name: 'lamp', icon: 'svgo-duo-lamp' },
  { name: 'laptop', icon: 'svgo-duo-laptop' },
  { name: 'layers-minimalistic', icon: 'svgo-duo-layers-minimalistic' },
  { name: 'leaf', icon: 'svgo-duo-leaf' },
  { name: 'lightbulb', icon: 'svgo-duo-lightbulb' },
  { name: 'lightning', icon: 'svgo-duo-lightning' },
  { name: 'like', icon: 'svgo-duo-like' },
  { name: 'lock-keyhole', icon: 'svgo-duo-lock-keyhole' },
  { name: 'magic-stick-2', icon: 'svgo-duo-magic-stick-2' },
  { name: 'magic-stick-3', icon: 'svgo-duo-magic-stick-3' },
  { name: 'magic-stick', icon: 'svgo-duo-magic-stick' },
  { name: 'magnet', icon: 'svgo-duo-magnet' },
  { name: 'magnifer', icon: 'svgo-duo-magnifer' },
  { name: 'mailbox', icon: 'svgo-duo-mailbox' },
  { name: 'map-arrow-up', icon: 'svgo-duo-map-arrow-up' },
  { name: 'map-point-wave', icon: 'svgo-duo-map-point-wave' },
  { name: 'map', icon: 'svgo-duo-map' },
  { name: 'masks', icon: 'svgo-duo-masks' },
  { name: 'medal-ribbon-star', icon: 'svgo-duo-medal-ribbon-star' },
  { name: 'medal-star-circle', icon: 'svgo-duo-medal-star-circle' },
  { name: 'medal-star-square', icon: 'svgo-duo-medal-star-square' },
  { name: 'medical-kit', icon: 'svgo-duo-medical-kit' },
  { name: 'meditation-round', icon: 'svgo-duo-meditation-round' },
  { name: 'men', icon: 'svgo-duo-men' },
  { name: 'microphone-large', icon: 'svgo-duo-microphone-large' },
  { name: 'microphone', icon: 'svgo-duo-microphone' },
  { name: 'money-bag', icon: 'svgo-duo-money-bag' },
  { name: 'monitor-camera', icon: 'svgo-duo-monitor-camera' },
  { name: 'moon-fog', icon: 'svgo-duo-moon-fog' },
  { name: 'moon', icon: 'svgo-duo-moon' },
  { name: 'mouse', icon: 'svgo-duo-mouse' },
  { name: 'music-note-2', icon: 'svgo-duo-music-note-2' },
  { name: 'music-note-3', icon: 'svgo-duo-music-note-3' },
  { name: 'notebook', icon: 'svgo-duo-notebook' },
  { name: 'notes-minimalistic', icon: 'svgo-duo-notes-minimalistic' },
  { name: 'notification-unread-lines', icon: 'svgo-duo-notification-unread-lines' },
  { name: 'oven-mitts', icon: 'svgo-duo-oven-mitts' },
  { name: 'paint-roller', icon: 'svgo-duo-paint-roller' },
  { name: 'palette-round', icon: 'svgo-duo-palette-round' },
  { name: 'pallete-2', icon: 'svgo-duo-pallete-2' },
  { name: 'panorama', icon: 'svgo-duo-panorama' },
  { name: 'paper-bin', icon: 'svgo-duo-paper-bin' },
  { name: 'paperclip', icon: 'svgo-duo-paperclip' },
  { name: 'passport', icon: 'svgo-duo-passport' },
  { name: 'paw', icon: 'svgo-duo-paw' },
  { name: 'pen', icon: 'svgo-duo-pen' },
  { name: 'perfume', icon: 'svgo-duo-perfume' },
  { name: 'pill', icon: 'svgo-duo-pill' },
  { name: 'pin-list', icon: 'svgo-duo-pin-list' },
  { name: 'pin', icon: 'svgo-duo-pin' },
  { name: 'pipette', icon: 'svgo-duo-pipette' },
  { name: 'plain-2', icon: 'svgo-duo-plain-2' },
  { name: 'planet-2', icon: 'svgo-duo-planet-2' },
  { name: 'planet-3', icon: 'svgo-duo-planet-3' },
  { name: 'plug-circle', icon: 'svgo-duo-plug-circle' },
  { name: 'presentation-graph', icon: 'svgo-duo-presentation-graph' },
  { name: 'printer-2', icon: 'svgo-duo-printer-2' },
  { name: 'printer', icon: 'svgo-duo-printer' },
  { name: 'projector', icon: 'svgo-duo-projector' },
  { name: 'pulse-2', icon: 'svgo-duo-pulse-2' },
  { name: 'qr-code', icon: 'svgo-duo-qr-code' },
  { name: 'radar-2', icon: 'svgo-duo-radar-2' },
  { name: 'radio-minimalistic', icon: 'svgo-duo-radio-minimalistic' },
  { name: 'radio', icon: 'svgo-duo-radio' },
  { name: 'ranking', icon: 'svgo-duo-ranking' },
  { name: 'reel', icon: 'svgo-duo-reel' },
  { name: 'remote-controller', icon: 'svgo-duo-remote-controller' },
  { name: 'rocket-2', icon: 'svgo-duo-rocket-2' },
  { name: 'rugby', icon: 'svgo-duo-rugby' },
  { name: 'ruler-angular', icon: 'svgo-duo-ruler-angular' },
  { name: 'ruler-pen', icon: 'svgo-duo-ruler-pen' },
  { name: 'ruler', icon: 'svgo-duo-ruler' },
  { name: 'running-2', icon: 'svgo-duo-running-2' },
  { name: 'scissors', icon: 'svgo-duo-scissors' },
  { name: 'server-path', icon: 'svgo-duo-server-path' },
  { name: 'server', icon: 'svgo-duo-server' },
  { name: 'settings', icon: 'svgo-duo-settings' },
  { name: 'shop-2', icon: 'svgo-duo-shop-2' },
  { name: 'sim-card-minimalistic', icon: 'svgo-duo-sim-card-minimalistic' },
  { name: 'siren-rounded', icon: 'svgo-duo-siren-rounded' },
  { name: 'skateboarding-round', icon: 'svgo-duo-skateboarding-round' },
  { name: 'skirt', icon: 'svgo-duo-skirt' },
  { name: 'sledgehammer', icon: 'svgo-duo-sledgehammer' },
  { name: 'sleeping', icon: 'svgo-duo-sleeping' },
  { name: 'smart-speaker-minimalistic', icon: 'svgo-duo-smart-speaker-minimalistic' },
  { name: 'smart-vacuum-cleaner', icon: 'svgo-duo-smart-vacuum-cleaner' },
  { name: 'snowflake', icon: 'svgo-duo-snowflake' },
  { name: 'sofa-3', icon: 'svgo-duo-sofa-3' },
  { name: 'sofa', icon: 'svgo-duo-sofa' },
  { name: 'speaker', icon: 'svgo-duo-speaker' },
  { name: 'square-academic-cap', icon: 'svgo-duo-square-academic-cap' },
  { name: 'star', icon: 'svgo-duo-star' },
  { name: 'stars-line', icon: 'svgo-duo-stars-line' },
  { name: 'station-minimalistic', icon: 'svgo-duo-station-minimalistic' },
  { name: 'stethoscope', icon: 'svgo-duo-stethoscope' },
  { name: 'stream', icon: 'svgo-duo-stream' },
  { name: 'streets-map-point', icon: 'svgo-duo-streets-map-point' },
  { name: 'stretching-round', icon: 'svgo-duo-stretching-round' },
  { name: 'suitcase-lines', icon: 'svgo-duo-suitcase-lines' },
  { name: 'suitcase-tag', icon: 'svgo-duo-suitcase-tag' },
  { name: 'suitcase', icon: 'svgo-duo-suitcase' },
  { name: 'sun-2', icon: 'svgo-duo-sun-2' },
  { name: 'swimming', icon: 'svgo-duo-swimming' },
  { name: 'syringe', icon: 'svgo-duo-syringe' },
  { name: 't-shirt', icon: 'svgo-duo-t-shirt' },
  { name: 'tag', icon: 'svgo-duo-tag' },
  { name: 'target', icon: 'svgo-duo-target' },
  { name: 'tea-cup', icon: 'svgo-duo-tea-cup' },
  { name: 'telescope', icon: 'svgo-duo-telescope' },
  { name: 'temperature', icon: 'svgo-duo-temperature' },
  { name: 'tennis-2', icon: 'svgo-duo-tennis-2' },
  { name: 'tennis', icon: 'svgo-duo-tennis' },
  { name: 'test-tube-minimalistic', icon: 'svgo-duo-test-tube-minimalistic' },
  { name: 'thermometer', icon: 'svgo-duo-thermometer' },
  { name: 'ticker-star', icon: 'svgo-duo-ticker-star' },
  { name: 'tornado-small', icon: 'svgo-duo-tornado-small' },
  { name: 'trash-bin-trash', icon: 'svgo-duo-trash-bin-trash' },
  { name: 'treadmill', icon: 'svgo-duo-treadmill' },
  { name: 'turntable', icon: 'svgo-duo-turntable' },
  { name: 'tv', icon: 'svgo-duo-tv' },
  { name: 'ufo', icon: 'svgo-duo-ufo' },
  { name: 'umbrella', icon: 'svgo-duo-umbrella' },
  { name: 'user', icon: 'svgo-duo-user' },
  { name: 'videocamera-record', icon: 'svgo-duo-videocamera-record' },
  { name: 'volleyball', icon: 'svgo-duo-volleyball' },
  { name: 'walking', icon: 'svgo-duo-walking' },
  { name: 'wallet-money', icon: 'svgo-duo-wallet-money' },
  { name: 'wallet', icon: 'svgo-duo-wallet' },
  { name: 'wallpaper', icon: 'svgo-duo-wallpaper' },
  { name: 'washing-machine-minimalistic', icon: 'svgo-duo-washing-machine-minimalistic' },
  { name: 'washing-machine', icon: 'svgo-duo-washing-machine' },
  { name: 'watch-square', icon: 'svgo-duo-watch-square' },
  { name: 'water-sun', icon: 'svgo-duo-water-sun' },
  { name: 'water', icon: 'svgo-duo-water' },
  { name: 'waterdrop', icon: 'svgo-duo-waterdrop' },
  { name: 'waterdrops', icon: 'svgo-duo-waterdrops' },
  { name: 'weigher', icon: 'svgo-duo-weigher' },
  { name: 'whisk', icon: 'svgo-duo-whisk' },
  { name: 'wi-fi-router', icon: 'svgo-duo-wi-fi-router' },
  { name: 'wineglass-triangle', icon: 'svgo-duo-wineglass-triangle' },
  { name: 'wineglass', icon: 'svgo-duo-wineglass' },
  { name: 'wireless-charge', icon: 'svgo-duo-wireless-charge' },
  { name: 'women', icon: 'svgo-duo-women' },
]

export const fluentListIcons = [
  // { name: 'car / vehicle', icon: 'svgo-fluent-vehicle-car-profile-24-regular' },
  // { name: 'food', icon: 'svgo-fluent-food-24-regular' },
  // { name: 'food / pizza', icon: 'svgo-fluent-food-pizza-20-regular' },
  // { name: 'food / toast / bread', icon: 'svgo-fluent-food-toast-20-regular' },
  // { name: 'building / home', icon: 'svgo-fluent-building-home-16-regular' },
  // { name: 'building / home / garage', icon: 'svgo-fluent-home-garage-20-regular' },
  // { name: 'building / home / garage', icon: 'svgo-fluent-home-garage-20-regular' },
  // { name: 'food / chicken', icon: 'svgo-fluent-food_chicken-leg-16-regular' },

  { name: 'building-24-regular', icon: 'svgo-fluent-building-24-regular' },
  { name: 'building-bank-20-regular', icon: 'svgo-fluent-building-bank-20-regular' },
  { name: 'building-home-16-regular', icon: 'svgo-fluent-building-home-16-regular' },
  { name: 'building-mosque-20-regular', icon: 'svgo-fluent-building-mosque-20-regular' },
  { name: 'building-multiple-20-regular', icon: 'svgo-fluent-building-multiple-20-regular' },
  { name: 'building-townhouse-20-regular', icon: 'svgo-fluent-building-townhouse-20-regular' },
  { name: 'crown-20-regular', icon: 'svgo-fluent-crown-20-regular' },
  { name: 'dentist-20-regular', icon: 'svgo-fluent-dentist-20-regular' },
  { name: 'desktop-sync-24-regular', icon: 'svgo-fluent-desktop-sync-24-regular' },
  { name: 'dishwasher-20-regular', icon: 'svgo-fluent-dishwasher-20-regular' },
  { name: 'emoji-24-regular', icon: 'svgo-fluent-emoji-24-regular' },
  { name: 'food-24-regular', icon: 'svgo-fluent-food-24-regular' },
  { name: 'food-apple-20-regular', icon: 'svgo-fluent-food-apple-20-regular' },
  { name: 'food-chicken-leg-16-regular', icon: 'svgo-fluent-food-chicken-leg-16-regular' },
  { name: 'food-egg-20-regular', icon: 'svgo-fluent-food-egg-20-regular' },
  { name: 'food-fish-20-regular', icon: 'svgo-fluent-food-fish-20-regular' },
  { name: 'food-pizza-20-regular', icon: 'svgo-fluent-food-pizza-20-regular' },
  { name: 'food-toast-20-regular', icon: 'svgo-fluent-food-toast-20-regular' },
  { name: 'home-garage-20-regular', icon: 'svgo-fluent-home-garage-20-regular' },
  { name: 'rocket-24-regular', icon: 'svgo-fluent-rocket-24-regular' },
  { name: 'savings-24-regular', icon: 'svgo-fluent-savings-24-regular' },
  { name: 'shifts-20-regular', icon: 'svgo-fluent-shifts-20-regular' },
  { name: 'spatula-spoon-24-regular', icon: 'svgo-fluent-spatula-spoon-24-regular' },
  { name: 'stack-star-20-regular', icon: 'svgo-fluent-stack-star-20-regular' },
  { name: 'vehicle-bicycle-20-regular', icon: 'svgo-fluent-vehicle-bicycle-20-regular' },
  { name: 'vehicle-car-profile-24-regular', icon: 'svgo-fluent-vehicle-car-profile-24-regular' },
  { name: 'wallet-20-regular', icon: 'svgo-fluent-wallet-20-regular' },
]

export const avatarListIcons = [
  { name: 'actor chaplin comedy', icon: 'svgo-avatar-actor-chaplin-comedy-svgrepo-com' },
  { name: 'addicted drawlove', icon: 'svgo-avatar-addicted-draw-love-svgrepo-com' },
  { name: 'afro-avatar-male-2-svgrepo-com', icon: 'svgo-avatar-afro-avatar-male-2-svgrepo-com' },
  { name: 'afro-avatar-male-svgrepo-com', icon: 'svgo-avatar-afro-avatar-male-svgrepo-com' },
  { name: 'afro-boy-child-svgrepo-com', icon: 'svgo-avatar-afro-boy-child-svgrepo-com' },
  { name: 'afro-female-person-svgrepo-com', icon: 'svgo-avatar-afro-female-person-svgrepo-com' },
  { name: 'alien-avatar-space-svgrepo-com', icon: 'svgo-avatar-alien-avatar-space-svgrepo-com' },
  { name: 'animal-avatar-bear-svgrepo-com', icon: 'svgo-avatar-animal-avatar-bear-svgrepo-com' },
  { name: 'animal-avatar-mutton-svgrepo-com', icon: 'svgo-avatar-animal-avatar-mutton-svgrepo-com' },
  { name: 'anime-away-face-svgrepo-com', icon: 'svgo-avatar-anime-away-face-svgrepo-com' },
  { name: 'apple-avatar-illness-svgrepo-com', icon: 'svgo-avatar-apple-avatar-illness-svgrepo-com' },
  { name: 'artist-avatar-marilyn-svgrepo-com', icon: 'svgo-avatar-artist-avatar-marilyn-svgrepo-com' },
  { name: 'avatar-avocado-food-svgrepo-com', icon: 'svgo-avatar-avocado-food-svgrepo-com' },
  { name: 'avatar-bad-breaking-svgrepo-com', icon: 'svgo-avatar-bad-breaking-svgrepo-com' },
  { name: 'avatar-batman-comics-svgrepo-com', icon: 'svgo-avatar-batman-comics-svgrepo-com' },
  { name: 'avatar-boy-kid-svgrepo-com', icon: 'svgo-avatar-boy-kid-svgrepo-com' },
  { name: 'avatar-boy-male-svgrepo-com', icon: 'svgo-avatar-boy-male-svgrepo-com' },
  { name: 'avatar-bug-insect-svgrepo-com', icon: 'svgo-avatar-bug-insect-svgrepo-com' },
  { name: 'avatar-cacti-cactus-svgrepo-com', icon: 'svgo-avatar-cacti-cactus-svgrepo-com' },
  { name: 'avatar-child-girl-svgrepo-com', icon: 'svgo-avatar-child-girl-svgrepo-com' },
  { name: 'avatar-cloud-crying-svgrepo-com', icon: 'svgo-avatar-cloud-crying-svgrepo-com' },
  { name: 'avatar-coffee-cup-svgrepo-com', icon: 'svgo-avatar-coffee-cup-svgrepo-com' },
  { name: 'avatar-dead-monster-svgrepo-com', icon: 'svgo-avatar-dead-monster-svgrepo-com' },
  { name: 'avatar-einstein-professor-svgrepo-com', icon: 'svgo-avatar-einstein-professor-svgrepo-com' },
  { name: 'avatar-elderly-grandma-svgrepo-com', icon: 'svgo-avatar-elderly-grandma-svgrepo-com' },
  { name: 'avatar-female-girl-svgrepo-com', icon: 'svgo-avatar-female-girl-svgrepo-com' },
  { name: 'avatar-female-portrait-2-svgrepo-com', icon: 'svgo-avatar-female-portrait-2-svgrepo-com' },
  { name: 'avatar-female-portrait-svgrepo-com', icon: 'svgo-avatar-female-portrait-svgrepo-com' },
  { name: 'avatar-geisha-japanese-svgrepo-com', icon: 'svgo-avatar-geisha-japanese-svgrepo-com' },
  { name: 'avatar-hindi-indian-svgrepo-com', icon: 'svgo-avatar-hindi-indian-svgrepo-com' },
  { name: 'avatar-joker-squad-svgrepo-com', icon: 'svgo-avatar-joker-squad-svgrepo-com' },
  { name: 'avatar-lazybones-sloth-svgrepo-com', icon: 'svgo-avatar-lazybones-sloth-svgrepo-com' },
  { name: 'avatar-male-man-svgrepo-com', icon: 'svgo-avatar-male-man-svgrepo-com' },
  { name: 'avatar-male-ozzy-svgrepo-com', icon: 'svgo-avatar-male-ozzy-svgrepo-com' },
  { name: 'avatar-male-president-svgrepo-com', icon: 'svgo-avatar-male-president-svgrepo-com' },
  { name: 'avatar-man-muslim-svgrepo-com', icon: 'svgo-avatar-man-muslim-svgrepo-com' },
  { name: 'avatar-man-person-svgrepo-com', icon: 'svgo-avatar-man-person-svgrepo-com' },
  { name: 'avatar-muslim-paranja-svgrepo-com', icon: 'svgo-avatar-muslim-paranja-svgrepo-com' },
  { name: 'avatar-nun-sister-svgrepo-com', icon: 'svgo-avatar-nun-sister-svgrepo-com' },
  { name: 'avatar-person-pilot-svgrepo-com', icon: 'svgo-avatar-person-pilot-svgrepo-com' },
  { name: 'baby-child-kid-svgrepo-com', icon: 'svgo-avatar-baby-child-kid-svgrepo-com' },
  { name: 'beard-hipster-male-svgrepo-com', icon: 'svgo-avatar-beard-hipster-male-svgrepo-com' },
  { name: 'boy-indian-kid-svgrepo-com', icon: 'svgo-avatar-boy-indian-kid-svgrepo-com' },
  { name: 'builder-helmet-worker-svgrepo-com', icon: 'svgo-avatar-builder-helmet-worker-svgrepo-com' },
  { name: 'child-girl-kid-svgrepo-com', icon: 'svgo-avatar-child-girl-kid-svgrepo-com' },
  { name: 'christmas-clous-santa-svgrepo-com', icon: 'svgo-avatar-christmas-clous-santa-svgrepo-com' },
  { name: 'fighter-luchador-man-svgrepo-com', icon: 'svgo-avatar-fighter-luchador-man-svgrepo-com' },
  { name: 'friday-halloween-jason-svgrepo-com', icon: 'svgo-avatar-friday-halloween-jason-svgrepo-com' },
  { name: 'indian-male-man-svgrepo-com', icon: 'svgo-avatar-indian-male-man-svgrepo-com' },
  { name: 'indian-man-sikh-svgrepo-com', icon: 'svgo-avatar-indian-man-sikh-svgrepo-com' },
  { name: 'male-man-old-svgrepo-com', icon: 'svgo-avatar-male-man-old-svgrepo-com' },

  //
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg
  // .svg

  { name: 'browser-analytics-svgrepo-com', icon: 'svgo-avatar-browser-analytics-svgrepo-com' },
  { name: 'coin-svgrepo-com', icon: 'svgo-avatar-coin-svgrepo-com' },
  { name: 'credit-card-svgrepo-com', icon: 'svgo-avatar-credit-card-svgrepo-com' },
  { name: 'discount-sign-money-svgrepo-com', icon: 'svgo-avatar-discount-sign-money-svgrepo-com' },
  { name: 'light-bulb-idea-svgrepo-com', icon: 'svgo-avatar-light-bulb-idea-svgrepo-com' },
  { name: 'payment-cards-money-svgrepo-com', icon: 'svgo-avatar-payment-cards-money-svgrepo-com' },
  { name: 'piggy-bank-svgrepo-com', icon: 'svgo-avatar-piggy-bank-svgrepo-com' },
  { name: 'safebox-bank-svgrepo-com', icon: 'svgo-avatar-safebox-bank-svgrepo-com' },
  { name: 'tag-price-label-svgrepo-com', icon: 'svgo-avatar-tag-price-label-svgrepo-com' },
  { name: 'wallet-money-business-svgrepo-com', icon: 'svgo-avatar-wallet-money-business-svgrepo-com' },
  { name: 'wallet-svgrepo-com-2', icon: 'svgo-avatar-wallet-svgrepo-com-2' },
  { name: 'wallet-svgrepo-com', icon: 'svgo-avatar-wallet-svgrepo-com' },
]



export const custom = {
  exchange: 'svgo-custom-exchange'
}

