export const duoToneListIcons = [
  { name: 'plaster adhesive medical', icon: 'svgo-duo-adhesive-plaster-2' },
  { name: 'plaster adhesive medical', icon: 'svgo-duo-adhesive-plaster' },
  { name: 'airbuds case audio', icon: 'svgo-duo-airbuds-case' },
  { name: 'airbuds case audio', icon: 'svgo-duo-airbuds' },
  { name: 'alarm clock time', icon: 'svgo-duo-alarm' },
  { name: 'album record collection anthology', icon: 'svgo-duo-album' },
  { name: 'archive storage repository vault', icon: 'svgo-duo-archive-up-minimlistic' },
  { name: 'archive storage repository vault', icon: 'svgo-duo-archive' },
  { name: 'armchair-2 seat chair recliner', icon: 'svgo-duo-armchair-2' },
  { name: 'armchair seat chair recliner', icon: 'svgo-duo-armchair' },
  { name: 'asteroid meteoroid rock space', icon: 'svgo-duo-asteroid' },
  { name: 'atom molecule particle element', icon: 'svgo-duo-atom' },
  { name: 'backpack rucksack knapsack bag', icon: 'svgo-duo-backpack' },
  { name: 'bacteria microbe germ microorganism', icon: 'svgo-duo-bacteria' },
  { name: 'bag-2 purse satchel tote', icon: 'svgo-duo-bag-2' },
  { name: 'bag-3 handbag carryall pouch', icon: 'svgo-duo-bag-3' },
  { name: 'bag-4 backpack knapsack rucksack', icon: 'svgo-duo-bag-4' },
  { name: 'bag-5 duffel holdall weekender', icon: 'svgo-duo-bag-5' },
  { name: 'bag-heart love fashion accessory', icon: 'svgo-duo-bag-heart' },
  { name: 'bag carrier sack pack', icon: 'svgo-duo-bag' },
  { name: 'balloon inflatable float bubble', icon: 'svgo-duo-balloon' },
  { name: 'balls spheres orbs globes', icon: 'svgo-duo-balls' },
  { name: 'bank note banknote currency money', icon: 'svgo-duo-banknote-2' },
  { name: 'banknote bill currency cash', icon: 'svgo-duo-banknote' },
  { name: 'bar-chair stool seat perch', icon: 'svgo-duo-bar-chair' },
  { name: 'basketball hoop court dribble', icon: 'svgo-duo-basketball' },
  { name: 'bath tub shower washroom', icon: 'svgo-duo-bath' },
  { name: 'battery-charge power energy accumulator', icon: 'svgo-duo-battery-charge' },
  { name: 'bed mattress bunk cot', icon: 'svgo-duo-bed' },
  { name: 'bedside table nightstand drawer cabinet', icon: 'svgo-duo-bedside-table-2' },
  { name: 'bedside table nightstand drawer cabinet', icon: 'svgo-duo-bedside-table-3' },
  { name: 'bedside table nightstand drawer cabinet', icon: 'svgo-duo-bedside-table-4' },
  { name: 'bedside table nightstand drawer cabinet', icon: 'svgo-duo-bedside-table' },
  { name: 'body physique figure form', icon: 'svgo-duo-body' },
  { name: 'bolt lightning thunder electricity', icon: 'svgo-duo-bolt-circle' },
  { name: 'bone skeleton marrow osseous', icon: 'svgo-duo-bone' },
  { name: 'bonfire campfire flame blaze', icon: 'svgo-duo-bonfire' },
  { name: 'book bookmark literature novel', icon: 'svgo-duo-book-bookmark-minimalistic' },
  { name: 'bookmark-square tag marker flag', icon: 'svgo-duo-bookmark-square' },
  { name: 'bottle container flask vessel', icon: 'svgo-duo-bottle' },
  { name: 'bowling pins alley strike', icon: 'svgo-duo-bowling' },
  { name: 'box carton package container', icon: 'svgo-duo-box' },
  { name: 'calculator math computation device', icon: 'svgo-duo-calculator' },
  { name: 'calendar-add schedule planner date', icon: 'svgo-duo-calendar-add' },
  { name: 'calendar schedule planner date', icon: 'svgo-duo-calendar' },
  { name: 'camera-minimalistic photo lens capture', icon: 'svgo-duo-camera-minimalistic' },
  { name: 'camera photo lens capture', icon: 'svgo-duo-camera' },
  { name: 'card-2 credit debit payment', icon: 'svgo-duo-card-2' },
  { name: 'card-recive payment transaction deposit', icon: 'svgo-duo-card-recive' },
  { name: 'card-search find lookup query', icon: 'svgo-duo-card-search' },
  { name: 'card-send payment transaction transfer', icon: 'svgo-duo-card-send' },
  { name: 'card-transfer payment transaction exchange', icon: 'svgo-duo-card-transfer' },
  { name: 'card credit debit payment', icon: 'svgo-duo-card' },
  { name: 'cardholder wallet purse case', icon: 'svgo-duo-cardholder' },
  { name: 'cart-3 shopping basket trolley', icon: 'svgo-duo-cart-3' },
  { name: 'cart-check shopping verify confirm', icon: 'svgo-duo-cart-check' },
  { name: 'cart shopping basket trolley', icon: 'svgo-duo-cart' },
  { name: 'case-minimalistic briefcase suitcase bag', icon: 'svgo-duo-case-minimalistic' },
  { name: 'case-round luggage suitcase bag', icon: 'svgo-duo-case-round' },
  { name: 'cash-out withdraw money atm', icon: 'svgo-duo-cash-out' },
  { name: 'cassette-2 tape audio record', icon: 'svgo-duo-cassette-2' },
  { name: 'chair-2 seat furniture stool', icon: 'svgo-duo-chair-2' },
  { name: 'chair seat furniture stool', icon: 'svgo-duo-chair' },
  { name: 'chandelier light fixture lamp', icon: 'svgo-duo-chandelier' },
  { name: 'chart-2 graph diagram analytics', icon: 'svgo-duo-chart-2' },
  { name: 'chat-square-call message phone communicate', icon: 'svgo-duo-chat-square-call' },
  { name: 'chat-square-like message approval thumbs-up', icon: 'svgo-duo-chat-square-like' },
  { name: 'chat-square message conversation dialogue', icon: 'svgo-duo-chat-square' },
  { name: 'chef-hat-heart cooking love passion', icon: 'svgo-duo-chef-hat-heart' },
  { name: 'chef-hat-minimalistic cooking culinary toque', icon: 'svgo-duo-chef-hat-minimalistic' },
  { name: 'clapperboard-edit film movie modify', icon: 'svgo-duo-clapperboard-edit' },
  { name: 'clapperboard-open-play film movie start', icon: 'svgo-duo-clapperboard-open-play' },
  { name: 'clapperboard-text film movie subtitle', icon: 'svgo-duo-clapperboard-text' },
  { name: 'clipboard-heart favorite love list', icon: 'svgo-duo-clipboard-heart' },
  { name: 'clipboard-list checklist inventory tasks', icon: 'svgo-duo-clipboard-list' },
  { name: 'closet-2 wardrobe cabinet armoire', icon: 'svgo-duo-closet-2' },
  { name: 'closet wardrobe cabinet armoire', icon: 'svgo-duo-closet' },
  { name: 'cloud-bolt-minimalistic storm lightning weather', icon: 'svgo-duo-cloud-bolt-minimalistic' },
  { name: 'cloud-rain weather precipitation shower', icon: 'svgo-duo-cloud-rain' },
  { name: 'code programming development syntax', icon: 'svgo-duo-code' },
  { name: 'colour-tuneing adjustment hue saturation', icon: 'svgo-duo-colour-tuneing' },
  { name: 'condicioner air-conditioning cooling hvac', icon: 'svgo-duo-condicioner' },
  { name: 'confetti-minimalistic celebration party festive', icon: 'svgo-duo-confetti-minimalistic' },
  { name: 'corkscrew bottle-opener wine-opener opener', icon: 'svgo-duo-corkscrew' },
  { name: 'cosmetic makeup beauty skincare', icon: 'svgo-duo-cosmetic' },
  { name: 'cpu processor chip microprocessor', icon: 'svgo-duo-cpu' },
  { name: 'crown-line royalty monarch diadem', icon: 'svgo-duo-crown-line' },
  { name: 'cup-first winner champion trophy', icon: 'svgo-duo-cup-first' },
  { name: 'cup-hot coffee tea beverage', icon: 'svgo-duo-cup-hot' },
  { name: 'cup-paper disposable drink container', icon: 'svgo-duo-cup-paper' },
  { name: 'cup mug glass tumbler', icon: 'svgo-duo-cup' },
  { name: 'database storage information repository', icon: 'svgo-duo-database' },
  { name: 'delivery shipping transport logistics', icon: 'svgo-duo-delivery' },
  { name: 'devices gadgets electronics technology', icon: 'svgo-duo-devices' },
  { name: 'diagram-down chart graph decline', icon: 'svgo-duo-diagram-down' },
  { name: 'diploma certificate degree qualification', icon: 'svgo-duo-diploma' },
  { name: 'diskette floppy-disk storage save', icon: 'svgo-duo-diskette' },
  { name: 'display monitor screen television', icon: 'svgo-duo-display' },
  { name: 'dna genetics helix chromosome', icon: 'svgo-duo-dna' },
  { name: 'document-add file create new', icon: 'svgo-duo-document-add' },
  { name: 'documents-minimalistic files papers records', icon: 'svgo-duo-documents-minimalistic' },
  { name: 'dollar money currency cash', icon: 'svgo-duo-dollar' },
  { name: 'donut-bitten pastry dessert snack', icon: 'svgo-duo-donut-bitten' },
  { name: 'dumbbell-large weight fitness exercise', icon: 'svgo-duo-dumbbell-large' },
  { name: 'dumbbell-small weight fitness exercise', icon: 'svgo-duo-dumbbell-small' },
  { name: 'earth globe planet world', icon: 'svgo-duo-earth' },
  { name: 'emoji-funny-square face expression emotion', icon: 'svgo-duo-emoji-funny-square' },
  { name: 'end-call-rounded hang-up terminate disconnect', icon: 'svgo-duo-end-call-rounded' },
  { name: 'eraser delete remove erase', icon: 'svgo-duo-eraser' },
  { name: 'euro money currency cash', icon: 'svgo-duo-euro' },
  { name: 'eye vision sight view', icon: 'svgo-duo-eye' },
  { name: 'face-scan-square recognition biometric security', icon: 'svgo-duo-face-scan-square' },
  { name: 'filter sort refine sieve', icon: 'svgo-duo-filter' },
  { name: 'fire flame blaze inferno', icon: 'svgo-duo-fire' },
  { name: 'flag banner pennant ensign', icon: 'svgo-duo-flag' },
  { name: 'flame fire blaze burn', icon: 'svgo-duo-flame' },
  { name: 'flash-drive usb thumbdrive storage', icon: 'svgo-duo-flash-drive' },
  { name: 'flashlight-on torch beam light', icon: 'svgo-duo-flashlight-on' },
  { name: 'floor-lamp-minimalistic light illumination standing', icon: 'svgo-duo-floor-lamp-minimalistic' },
  { name: 'floor-lamp light illumination standing', icon: 'svgo-duo-floor-lamp' },
  { name: 'football soccer ball sport', icon: 'svgo-duo-football' },
  { name: 'fridge refrigerator cooler icebox', icon: 'svgo-duo-fridge' },
  { name: 'fuel gas petrol energy', icon: 'svgo-duo-fuel' },
  { name: 'gallery-edit photos modify images', icon: 'svgo-duo-gallery-edit' },
  { name: 'gameboy console handheld nintendo', icon: 'svgo-duo-gameboy' },
  { name: 'gamepad-charge controller joystick power', icon: 'svgo-duo-gamepad-charge' },
  { name: 'ghost-smile spirit specter phantom', icon: 'svgo-duo-ghost-smile' },
  { name: 'gift present package surprise', icon: 'svgo-duo-gift' },
  { name: 'glasses spectacles eyewear vision', icon: 'svgo-duo-glasses' },
  { name: 'global worldwide international universal', icon: 'svgo-duo-global' },
  { name: 'globus earth sphere planet', icon: 'svgo-duo-globus' },
  { name: 'golf club sport course', icon: 'svgo-duo-golf' },
  { name: 'gps navigation location tracking', icon: 'svgo-duo-gps' },
  { name: 'hanger-2 clothes rack wardrobe', icon: 'svgo-duo-hanger-2' },
  { name: 'hanger clothes rack wardrobe', icon: 'svgo-duo-hanger' },
  { name: 'headphones-round-sound audio music listen', icon: 'svgo-duo-headphones-round-sound' },
  { name: 'headphones-square audio music listen', icon: 'svgo-duo-headphones-square' },
  { name: 'health wellness medical fitness', icon: 'svgo-duo-health' },
  { name: 'heart love romance affection', icon: 'svgo-duo-heart' },
  { name: 'hiking trekking walking outdoors', icon: 'svgo-duo-hiking' },
  { name: 'history-3 past chronicle record', icon: 'svgo-duo-history-3' },
  { name: 'home-angle-2 house residence dwelling', icon: 'svgo-duo-home-angle-2' },
  { name: 'hourglass-line timer sandglass countdown', icon: 'svgo-duo-hourglass-line' },
  { name: 'inbox-archive storage repository filing', icon: 'svgo-duo-inbox-archive' },
  { name: 'inbox-in receive incoming messages', icon: 'svgo-duo-inbox-in' },
  { name: 'incognito anonymous private hidden', icon: 'svgo-duo-incognito' },
  { name: 'iphone smartphone mobile device', icon: 'svgo-duo-iphone' },
  { name: 'jar-of-pills-2 medicine capsules tablets', icon: 'svgo-duo-jar-of-pills-2' },
  { name: 'jar-of-pills medicine capsules tablets', icon: 'svgo-duo-jar-of-pills' },
  { name: 'key unlock access security', icon: 'svgo-duo-key' },
  { name: 'keyboard typing input device', icon: 'svgo-duo-keyboard' },
  { name: 'ladle spoon scoop dipper', icon: 'svgo-duo-ladle' },
  { name: 'lamp light illumination fixture', icon: 'svgo-duo-lamp' },
  { name: 'laptop computer notebook portable', icon: 'svgo-duo-laptop' },
  { name: 'layers-minimalistic stack levels tiers', icon: 'svgo-duo-layers-minimalistic' },
  { name: 'leaf foliage nature greenery', icon: 'svgo-duo-leaf' },
  { name: 'lightbulb idea inspiration brightness', icon: 'svgo-duo-lightbulb' },
  { name: 'lightning bolt thunder flash', icon: 'svgo-duo-lightning' },
  { name: 'like thumbs-up approve favorite', icon: 'svgo-duo-like' },
  { name: 'lock-keyhole secure protect padlock', icon: 'svgo-duo-lock-keyhole' },
  { name: 'magic-stick-2 wand spell sorcery', icon: 'svgo-duo-magic-stick-2' },
  { name: 'magic-stick-3 wand spell sorcery', icon: 'svgo-duo-magic-stick-3' },
  { name: 'magic-stick wand spell sorcery', icon: 'svgo-duo-magic-stick' },
  { name: 'magnet attract magnetism pull', icon: 'svgo-duo-magnet' },
  { name: 'magnifer search zoom investigate', icon: 'svgo-duo-magnifer' },
  { name: 'mailbox postbox letterbox correspondence', icon: 'svgo-duo-mailbox' },
  { name: 'map-arrow-up navigation direction guidance', icon: 'svgo-duo-map-arrow-up' },
  { name: 'map-point-wave location ping signal', icon: 'svgo-duo-map-point-wave' },
  { name: 'map atlas chart cartography', icon: 'svgo-duo-map' },
  { name: 'masks theater drama comedy', icon: 'svgo-duo-masks' },
  { name: 'medal-ribbon-star award prize trophy', icon: 'svgo-duo-medal-ribbon-star' },
  { name: 'medal-star-circle award prize trophy', icon: 'svgo-duo-medal-star-circle' },
  { name: 'medal-star-square award prize trophy', icon: 'svgo-duo-medal-star-square' },
  { name: 'medical-kit first-aid emergency healthcare', icon: 'svgo-duo-medical-kit' },
  { name: 'meditation-round mindfulness yoga relaxation', icon: 'svgo-duo-meditation-round' },
  { name: 'men male gentleman guy', icon: 'svgo-duo-men' },
  { name: 'microphone-large audio voice recording', icon: 'svgo-duo-microphone-large' },
  { name: 'microphone audio voice recording', icon: 'svgo-duo-microphone' },
  { name: 'money-bag cash wealth finance', icon: 'svgo-duo-money-bag' },
  { name: 'monitor-camera display screen webcam', icon: 'svgo-duo-monitor-camera' },
  { name: 'moon-fog night mist haze', icon: 'svgo-duo-moon-fog' },
  { name: 'moon night lunar celestial', icon: 'svgo-duo-moon' },
  { name: 'mouse computer peripheral cursor', icon: 'svgo-duo-mouse' },
  { name: 'music-note-2 melody tune sound', icon: 'svgo-duo-music-note-2' },
  { name: 'music-note-3 melody tune sound', icon: 'svgo-duo-music-note-3' },
  { name: 'notebook journal diary planner', icon: 'svgo-duo-notebook' },
  { name: 'notes-minimalistic memo reminder jotting', icon: 'svgo-duo-notes-minimalistic' },
  { name: 'notification-unread-lines alert message ping', icon: 'svgo-duo-notification-unread-lines' },
  { name: 'oven-mitts gloves protection cooking', icon: 'svgo-duo-oven-mitts' },
  { name: 'paint-roller brush decorator tool', icon: 'svgo-duo-paint-roller' },
  { name: 'palette-round colors art painting', icon: 'svgo-duo-palette-round' },
  { name: 'pallete-2 colors art painting', icon: 'svgo-duo-pallete-2' },
  { name: 'panorama landscape vista wide-view', icon: 'svgo-duo-panorama' },
  { name: 'paper-bin trash recycle waste', icon: 'svgo-duo-paper-bin' },
  { name: 'paperclip attachment fastener clip', icon: 'svgo-duo-paperclip' },
  { name: 'passport identification travel document', icon: 'svgo-duo-passport' },
  { name: 'paw animal print footprint', icon: 'svgo-duo-paw' },
  { name: 'pen writing utensil instrument', icon: 'svgo-duo-pen' },
  { name: 'perfume fragrance scent cologne', icon: 'svgo-duo-perfume' },
  { name: 'pill medication capsule tablet', icon: 'svgo-duo-pill' },
  { name: 'pin-list bookmark save organize', icon: 'svgo-duo-pin-list' },
  { name: 'pin thumbtack fastener attach', icon: 'svgo-duo-pin' },
  { name: 'pipette dropper laboratory chemistry', icon: 'svgo-duo-pipette' },
  { name: 'plain-2 aircraft airplane jet', icon: 'svgo-duo-plain-2' },
  { name: 'planet-2 world globe sphere', icon: 'svgo-duo-planet-2' },
  { name: 'planet-3 world globe sphere', icon: 'svgo-duo-planet-3' },
  { name: 'plug-circle power outlet socket', icon: 'svgo-duo-plug-circle' },
  { name: 'presentation-graph chart diagram report', icon: 'svgo-duo-presentation-graph' },
  { name: 'printer-2 copier scanner device', icon: 'svgo-duo-printer-2' },
  { name: 'printer copier scanner device', icon: 'svgo-duo-printer' },
  { name: 'projector presentation display screen', icon: 'svgo-duo-projector' },
  { name: 'pulse-2 heartbeat rhythm wave', icon: 'svgo-duo-pulse-2' },
  { name: 'qr-code barcode scan matrix', icon: 'svgo-duo-qr-code' },
  { name: 'radar-2 detection scanning sensor', icon: 'svgo-duo-radar-2' },
  { name: 'radio-minimalistic broadcast tuner wireless', icon: 'svgo-duo-radio-minimalistic' },
  { name: 'radio broadcast tuner wireless', icon: 'svgo-duo-radio' },
  { name: 'ranking leaderboard position standing', icon: 'svgo-duo-ranking' },
  { name: 'reel film movie cinema', icon: 'svgo-duo-reel' },
  { name: 'remote-controller control device wireless', icon: 'svgo-duo-remote-controller' },
  { name: 'rocket-2 spaceship launch missile', icon: 'svgo-duo-rocket-2' },
  { name: 'rugby football sport ball', icon: 'svgo-duo-rugby' },
  { name: 'ruler-angular measure protractor geometry', icon: 'svgo-duo-ruler-angular' },
  { name: 'ruler-pen measure draw instrument', icon: 'svgo-duo-ruler-pen' },
  { name: 'ruler measure length scale', icon: 'svgo-duo-ruler' },
  { name: 'running-2 jogging sprint exercise', icon: 'svgo-duo-running-2' },
  { name: 'scissors cut snip shears', icon: 'svgo-duo-scissors' },
  { name: 'server-path network data connection', icon: 'svgo-duo-server-path' },
  { name: 'server database storage network', icon: 'svgo-duo-server' },
  { name: 'settings gear options preferences', icon: 'svgo-duo-settings' },
  { name: 'shop-2 store market retail', icon: 'svgo-duo-shop-2' },
  { name: 'sim-card-minimalistic phone mobile cellular', icon: 'svgo-duo-sim-card-minimalistic' },
  { name: 'siren-rounded alarm warning alert', icon: 'svgo-duo-siren-rounded' },
  { name: 'skateboarding-round skate board extreme', icon: 'svgo-duo-skateboarding-round' },
  { name: 'skirt garment clothing fashion', icon: 'svgo-duo-skirt' },
  { name: 'sledgehammer tool hammer mallet', icon: 'svgo-duo-sledgehammer' },
  { name: 'sleeping rest nap slumber', icon: 'svgo-duo-sleeping' },
  { name: 'smart-speaker-minimalistic assistant voice ai', icon: 'svgo-duo-smart-speaker-minimalistic' },
  { name: 'smart-vacuum-cleaner robotic automated housekeeping', icon: 'svgo-duo-smart-vacuum-cleaner' },
  { name: 'snowflake winter ice crystal', icon: 'svgo-duo-snowflake' },
  { name: 'sofa-3 couch settee furniture', icon: 'svgo-duo-sofa-3' },
  { name: 'sofa couch settee furniture', icon: 'svgo-duo-sofa' },
  { name: 'speaker audio sound music', icon: 'svgo-duo-speaker' },
  { name: 'square-academic-cap graduation mortarboard education', icon: 'svgo-duo-square-academic-cap' },
  { name: 'star celestial rating favorite', icon: 'svgo-duo-star' },
  { name: 'stars-line constellation sky night', icon: 'svgo-duo-stars-line' },
  { name: 'station-minimalistic transport terminal stop', icon: 'svgo-duo-station-minimalistic' },
  { name: 'stethoscope medical doctor health', icon: 'svgo-duo-stethoscope' },
  { name: 'stream flow current broadcast', icon: 'svgo-duo-stream' },
  { name: 'streets-map-point location navigation city', icon: 'svgo-duo-streets-map-point' },
  { name: 'stretching-round exercise flexibility yoga', icon: 'svgo-duo-stretching-round' },
  { name: 'suitcase-lines luggage baggage travel', icon: 'svgo-duo-suitcase-lines' },
  { name: 'suitcase-tag luggage baggage travel', icon: 'svgo-duo-suitcase-tag' },
  { name: 'suitcase luggage baggage travel', icon: 'svgo-duo-suitcase' },
  { name: 'sun-2 solar star daylight', icon: 'svgo-duo-sun-2' },
  { name: 'swimming pool water sport', icon: 'svgo-duo-swimming' },
  { name: 'syringe injection vaccine medical', icon: 'svgo-duo-syringe' },
  { name: 't-shirt clothing apparel fashion', icon: 'svgo-duo-t-shirt' },
  { name: 'tag label price marker', icon: 'svgo-duo-tag' },
  { name: 'target aim goal bullseye', icon: 'svgo-duo-target' },
  { name: 'tea-cup mug beverage drink', icon: 'svgo-duo-tea-cup' },
  { name: 'telescope astronomy space observation', icon: 'svgo-duo-telescope' },
  { name: 'temperature thermometer climate weather', icon: 'svgo-duo-temperature' },
  { name: 'tennis-2 racket sport ball', icon: 'svgo-duo-tennis-2' },
  { name: 'tennis racket sport ball', icon: 'svgo-duo-tennis' },
  { name: 'test-tube-minimalistic laboratory experiment science', icon: 'svgo-duo-test-tube-minimalistic' },
  { name: 'thermometer temperature measure gauge', icon: 'svgo-duo-thermometer' },
  { name: 'ticker-star favorite news feed', icon: 'svgo-duo-ticker-star' },
  { name: 'tornado-small twister cyclone funnel', icon: 'svgo-duo-tornado-small' },
  { name: 'trash-bin-trash garbage waste rubbish', icon: 'svgo-duo-trash-bin-trash' },
  { name: 'treadmill exercise fitness running', icon: 'svgo-duo-treadmill' },
  { name: 'turntable record player vinyl', icon: 'svgo-duo-turntable' },
  { name: 'tv television screen monitor', icon: 'svgo-duo-tv' },
  { name: 'ufo alien spacecraft flying-saucer', icon: 'svgo-duo-ufo' },
  { name: 'umbrella parasol rain shelter', icon: 'svgo-duo-umbrella' },
  { name: 'user person profile account', icon: 'svgo-duo-user' },
  { name: 'videocamera-record film shoot capture', icon: 'svgo-duo-videocamera-record' },
  { name: 'volleyball sport ball game', icon: 'svgo-duo-volleyball' },
  { name: 'walking stroll hike strolling', icon: 'svgo-duo-walking' },
  { name: 'wallet-money purse billfold finance', icon: 'svgo-duo-wallet-money' },
  { name: 'wallet purse billfold money', icon: 'svgo-duo-wallet' },
  { name: 'wallpaper decoration background interior', icon: 'svgo-duo-wallpaper' },
  { name: 'washing machine minimalistic laundry appliance cleaner', icon: 'svgo-duo-washing-machine-minimalistic' },
  { name: 'washing machine laundry appliance cleaner', icon: 'svgo-duo-washing-machine' },
  { name: 'watch square timepiece clock wristwatch', icon: 'svgo-duo-watch-square' },
  { name: 'water sun ocean wave sunshine', icon: 'svgo-duo-water-sun' },
  { name: 'water liquid h2o fluid', icon: 'svgo-duo-water' },
  { name: 'waterdrop droplet bead dewdrop', icon: 'svgo-duo-waterdrop' },
  { name: 'waterdrops droplets beads dewdrops', icon: 'svgo-duo-waterdrops' },
  { name: 'weigher scale balance measure', icon: 'svgo-duo-weigher' },
  { name: 'whisk mixer beater blender', icon: 'svgo-duo-whisk' },
  { name: 'wi-fi router modem network internet', icon: 'svgo-duo-wi-fi-router' },
  { name: 'wineglass triangle goblet chalice glass', icon: 'svgo-duo-wineglass-triangle' },
  { name: 'wineglass goblet chalice glass', icon: 'svgo-duo-wineglass' },
  { name: 'wireless charge cordless power battery', icon: 'svgo-duo-wireless-charge' },
  { name: 'women females ladies girls', icon: 'svgo-duo-women' },
]

export const fluentListIcons = [
  { name: 'bike', icon: 'svgo-fluent-bike' },
  { name: 'chick', icon: 'svgo-fluent-chick' },
  { name: 'dress', icon: 'svgo-fluent-dress' },
  { name: 'glasses', icon: 'svgo-fluent-glasses' },
  { name: 'hat', icon: 'svgo-fluent-hat' },
  { name: 'ice-cream', icon: 'svgo-fluent-ice-cream' },
  { name: 'ice-cream', icon: 'svgo-fluent-ice-cream' },
  { name: 'kid', icon: 'svgo-fluent-kid1' },
  { name: 'kid', icon: 'svgo-fluent-kid2' },
  { name: 'kid', icon: 'svgo-fluent-kid3' },
  { name: 'motorbike', icon: 'svgo-fluent-motorbike' },
  { name: 'pants', icon: 'svgo-fluent-pants' },
  { name: 'school', icon: 'svgo-fluent-school' },
  { name: 'scooter', icon: 'svgo-fluent-scooter' },
  { name: 'scooter', icon: 'svgo-fluent-scooter2' },
  { name: 'shoe', icon: 'svgo-fluent-shoe' },
  { name: 'underwear', icon: 'svgo-fluent-underwear' },
  { name: 'wifi internet', icon: 'svgo-fluent-wifi' },

  { name: 'building-24-regular', icon: 'svgo-fluent-building-24-regular' },
  { name: 'building-bank-20-regular', icon: 'svgo-fluent-building-bank-20-regular' },
  { name: 'building-home-16-regular', icon: 'svgo-fluent-building-home-16-regular' },
  { name: 'building-mosque-20-regular', icon: 'svgo-fluent-building-mosque-20-regular' },
  { name: 'building-multiple-20-regular', icon: 'svgo-fluent-building-multiple-20-regular' },
  { name: 'building-townhouse-20-regular', icon: 'svgo-fluent-building-townhouse-20-regular' },
  { name: 'crown-20-regular', icon: 'svgo-fluent-crown-20-regular' },
  { name: 'dentist-20-regular', icon: 'svgo-fluent-dentist-20-regular' },
  { name: 'desktop-sync-24-regular', icon: 'svgo-fluent-desktop-sync-24-regular' },
  { name: 'dishwasher-20-regular', icon: 'svgo-fluent-dishwasher-20-regular' },
  { name: 'emoji-24-regular', icon: 'svgo-fluent-emoji-24-regular' },
  { name: 'food-24-regular', icon: 'svgo-fluent-food-24-regular' },
  { name: 'food-apple-20-regular', icon: 'svgo-fluent-food-apple-20-regular' },
  { name: 'food-chicken-leg-16-regular', icon: 'svgo-fluent-food-chicken-leg-16-regular' },
  { name: 'food-egg-20-regular', icon: 'svgo-fluent-food-egg-20-regular' },
  { name: 'food-fish-20-regular', icon: 'svgo-fluent-food-fish-20-regular' },
  { name: 'food-pizza-20-regular', icon: 'svgo-fluent-food-pizza-20-regular' },
  { name: 'food-toast-20-regular', icon: 'svgo-fluent-food-toast-20-regular' },
  { name: 'home-garage-20-regular', icon: 'svgo-fluent-home-garage-20-regular' },
  { name: 'rocket-24-regular', icon: 'svgo-fluent-rocket-24-regular' },
  { name: 'savings-24-regular', icon: 'svgo-fluent-savings-24-regular' },
  { name: 'shifts-20-regular', icon: 'svgo-fluent-shifts-20-regular' },
  { name: 'spatula-spoon-24-regular', icon: 'svgo-fluent-spatula-spoon-24-regular' },
  { name: 'stack-star-20-regular', icon: 'svgo-fluent-stack-star-20-regular' },
  { name: 'vehicle-bicycle-20-regular', icon: 'svgo-fluent-vehicle-bicycle-20-regular' },
  { name: 'vehicle-car-profile-24-regular', icon: 'svgo-fluent-vehicle-car-profile-24-regular' },
  { name: 'wallet-20-regular', icon: 'svgo-fluent-wallet-20-regular' },
]

export const avatarListIcons = [
  { name: 'wallet', icon: 'svgo-avatar-wallet' },
  { name: 'wallet', icon: 'svgo-avatar-wallet2' },
  { name: 'umbrella', icon: 'svgo-avatar-umbrella' },
  { name: 'pouch', icon: 'svgo-avatar-pouch' },
  { name: 'piggy', icon: 'svgo-avatar-piggy' },
  { name: 'piggy', icon: 'svgo-avatar-piggy2' },
  { name: 'piggy', icon: 'svgo-avatar-piggy3' },
  { name: 'piggy', icon: 'svgo-avatar-piggy4' },
  { name: 'phone', icon: 'svgo-avatar-phone' },
  { name: 'education', icon: 'svgo-avatar-education' },
  { name: 'credit card', icon: 'svgo-avatar-card' },
  { name: 'credit card', icon: 'svgo-avatar-card2' },
  { name: 'money pile', icon: 'svgo-avatar-money-pile' },
  { name: 'graph', icon: 'svgo-avatar-graph' },
  { name: 'briefcase', icon: 'svgo-avatar-briefcase' },
  { name: 'briefcase', icon: 'svgo-avatar-briefcase2' },
  { name: 'box', icon: 'svgo-avatar-box' },
  { name: 'atm', icon: 'svgo-avatar-atm' },
  { name: 'atm', icon: 'svgo-avatar-atm2' },
  { name: 'bank', icon: 'svgo-avatar-bank' },
  { name: 'bank', icon: 'svgo-avatar-bank2' },
  { name: 'pot', icon: 'svgo-avatar-pot' },
  { name: 'rainbow', icon: 'svgo-avatar-rainbow' },
  { name: 'exchange money swap', icon: 'svgo-avatar-exchange' },
  { name: 'bag', icon: 'svgo-avatar-bag' },
  { name: 'bag', icon: 'svgo-avatar-bag2' },
  { name: 'bag', icon: 'svgo-avatar-bag3' },
  { name: 'bag', icon: 'svgo-avatar-bag4' },
  { name: 'bag', icon: 'svgo-avatar-bag5' },
  { name: 'coin', icon: 'svgo-avatar-coin' },
  { name: 'coin', icon: 'svgo-avatar-coin2' },
  { name: 'calculator', icon: 'svgo-avatar-calculator' },
  { name: 'diamond', icon: 'svgo-avatar-diamond' },
  { name: 'safe', icon: 'svgo-avatar-safe' },
  { name: 'safe', icon: 'svgo-avatar-safe2' },
  { name: 'money', icon: 'svgo-avatar-money' },
  { name: 'money', icon: 'svgo-avatar-money2' },
  { name: 'money', icon: 'svgo-avatar-money3' },
  { name: 'money', icon: 'svgo-avatar-money4' },
  { name: 'money', icon: 'svgo-avatar-money5' },
  { name: 'money cog', icon: 'svgo-avatar-money-cog' },

  { name: 'animal deer', icon: 'svgo-avatar-animal-deer' },
  { name: 'animal deer', icon: 'svgo-avatar-animal-deer2' },
  { name: 'animal dog', icon: 'svgo-avatar-animal-dog' },
  { name: 'animal racoon', icon: 'svgo-avatar-animal-racoon' },
  { name: 'animal rhino', icon: 'svgo-avatar-animal-rhino' },
  { name: 'animal giraffe', icon: 'svgo-avatar-animal-giraffe' },
  { name: 'animal monkey', icon: 'svgo-avatar-animal-monkey' },
  { name: 'animal monkey', icon: 'svgo-avatar-animal-monkey2' },
  { name: 'animal owl', icon: 'svgo-avatar-animal-owl' },
  { name: 'animal fox', icon: 'svgo-avatar-animal-fox' },
  { name: 'animal koala', icon: 'svgo-avatar-animal-koala' },
  { name: 'female', icon: 'svgo-avatar-female' },
  { name: 'male', icon: 'svgo-avatar-male' },

  { name: 'actor chaplin comedy', icon: 'svgo-avatar-actor-chaplin-comedy-svgrepo-com' },
  { name: 'addicted drawlove', icon: 'svgo-avatar-addicted-draw-love-svgrepo-com' },
  { name: 'afro-avatar-male-2-svgrepo-com', icon: 'svgo-avatar-afro-avatar-male-2-svgrepo-com' },
  { name: 'afro-avatar-male-svgrepo-com', icon: 'svgo-avatar-afro-avatar-male-svgrepo-com' },
  { name: 'afro-boy-child-svgrepo-com', icon: 'svgo-avatar-afro-boy-child-svgrepo-com' },
  { name: 'afro-female-person-svgrepo-com', icon: 'svgo-avatar-afro-female-person-svgrepo-com' },
  { name: 'alien-avatar-space-svgrepo-com', icon: 'svgo-avatar-alien-avatar-space-svgrepo-com' },
  { name: 'animal-avatar-bear-svgrepo-com', icon: 'svgo-avatar-animal-avatar-bear-svgrepo-com' },
  { name: 'animal-avatar-mutton-svgrepo-com', icon: 'svgo-avatar-animal-avatar-mutton-svgrepo-com' },
  { name: 'anime-away-face-svgrepo-com', icon: 'svgo-avatar-anime-away-face-svgrepo-com' },
  { name: 'apple-avatar-illness-svgrepo-com', icon: 'svgo-avatar-apple-avatar-illness-svgrepo-com' },
  { name: 'artist-avatar-marilyn-svgrepo-com', icon: 'svgo-avatar-artist-avatar-marilyn-svgrepo-com' },
  { name: 'avatar-avocado-food-svgrepo-com', icon: 'svgo-avatar-avocado-food-svgrepo-com' },
  { name: 'avatar-bad-breaking-svgrepo-com', icon: 'svgo-avatar-bad-breaking-svgrepo-com' },
  { name: 'avatar-batman-comics-svgrepo-com', icon: 'svgo-avatar-batman-comics-svgrepo-com' },
  { name: 'avatar-boy-kid-svgrepo-com', icon: 'svgo-avatar-boy-kid-svgrepo-com' },
  { name: 'avatar-boy-male-svgrepo-com', icon: 'svgo-avatar-boy-male-svgrepo-com' },
  { name: 'avatar-bug-insect-svgrepo-com', icon: 'svgo-avatar-bug-insect-svgrepo-com' },
  { name: 'avatar-cacti-cactus-svgrepo-com', icon: 'svgo-avatar-cacti-cactus-svgrepo-com' },
  { name: 'avatar-child-girl-svgrepo-com', icon: 'svgo-avatar-child-girl-svgrepo-com' },
  { name: 'avatar-cloud-crying-svgrepo-com', icon: 'svgo-avatar-cloud-crying-svgrepo-com' },
  { name: 'avatar-coffee-cup-svgrepo-com', icon: 'svgo-avatar-coffee-cup-svgrepo-com' },
  { name: 'avatar-dead-monster-svgrepo-com', icon: 'svgo-avatar-dead-monster-svgrepo-com' },
  { name: 'avatar-einstein-professor-svgrepo-com', icon: 'svgo-avatar-einstein-professor-svgrepo-com' },
  { name: 'avatar-elderly-grandma-svgrepo-com', icon: 'svgo-avatar-elderly-grandma-svgrepo-com' },
  { name: 'avatar-female-girl-svgrepo-com', icon: 'svgo-avatar-female-girl-svgrepo-com' },
  { name: 'avatar-female-portrait-2-svgrepo-com', icon: 'svgo-avatar-female-portrait-2-svgrepo-com' },
  { name: 'avatar-female-portrait-svgrepo-com', icon: 'svgo-avatar-female-portrait-svgrepo-com' },
  { name: 'avatar-geisha-japanese-svgrepo-com', icon: 'svgo-avatar-geisha-japanese-svgrepo-com' },
  { name: 'avatar-hindi-indian-svgrepo-com', icon: 'svgo-avatar-hindi-indian-svgrepo-com' },
  { name: 'avatar-joker-squad-svgrepo-com', icon: 'svgo-avatar-joker-squad-svgrepo-com' },
  { name: 'avatar-lazybones-sloth-svgrepo-com', icon: 'svgo-avatar-lazybones-sloth-svgrepo-com' },
  { name: 'avatar-male-man-svgrepo-com', icon: 'svgo-avatar-male-man-svgrepo-com' },
  { name: 'avatar-male-ozzy-svgrepo-com', icon: 'svgo-avatar-male-ozzy-svgrepo-com' },
  { name: 'avatar-male-president-svgrepo-com', icon: 'svgo-avatar-male-president-svgrepo-com' },
  { name: 'avatar-man-muslim-svgrepo-com', icon: 'svgo-avatar-man-muslim-svgrepo-com' },
  { name: 'avatar-man-person-svgrepo-com', icon: 'svgo-avatar-man-person-svgrepo-com' },
  { name: 'avatar-muslim-paranja-svgrepo-com', icon: 'svgo-avatar-muslim-paranja-svgrepo-com' },
  { name: 'avatar-nun-sister-svgrepo-com', icon: 'svgo-avatar-nun-sister-svgrepo-com' },
  { name: 'avatar-person-pilot-svgrepo-com', icon: 'svgo-avatar-person-pilot-svgrepo-com' },
  { name: 'baby-child-kid-svgrepo-com', icon: 'svgo-avatar-baby-child-kid-svgrepo-com' },
  { name: 'beard-hipster-male-svgrepo-com', icon: 'svgo-avatar-beard-hipster-male-svgrepo-com' },
  { name: 'boy-indian-kid-svgrepo-com', icon: 'svgo-avatar-boy-indian-kid-svgrepo-com' },
  { name: 'builder-helmet-worker-svgrepo-com', icon: 'svgo-avatar-builder-helmet-worker-svgrepo-com' },
  { name: 'child-girl-kid-svgrepo-com', icon: 'svgo-avatar-child-girl-kid-svgrepo-com' },
  { name: 'christmas-clous-santa-svgrepo-com', icon: 'svgo-avatar-christmas-clous-santa-svgrepo-com' },
  { name: 'fighter-luchador-man-svgrepo-com', icon: 'svgo-avatar-fighter-luchador-man-svgrepo-com' },
  { name: 'friday-halloween-jason-svgrepo-com', icon: 'svgo-avatar-friday-halloween-jason-svgrepo-com' },
  { name: 'indian-male-man-svgrepo-com', icon: 'svgo-avatar-indian-male-man-svgrepo-com' },
  { name: 'indian-man-sikh-svgrepo-com', icon: 'svgo-avatar-indian-man-sikh-svgrepo-com' },
  { name: 'male-man-old-svgrepo-com', icon: 'svgo-avatar-male-man-old-svgrepo-com' },

  { name: 'browser-analytics-svgrepo-com', icon: 'svgo-avatar-browser-analytics-svgrepo-com' },
  { name: 'coin-svgrepo-com', icon: 'svgo-avatar-coin-svgrepo-com' },
  { name: 'credit-card-svgrepo-com', icon: 'svgo-avatar-credit-card-svgrepo-com' },
  { name: 'discount-sign-money-svgrepo-com', icon: 'svgo-avatar-discount-sign-money-svgrepo-com' },
  { name: 'light-bulb-idea-svgrepo-com', icon: 'svgo-avatar-light-bulb-idea-svgrepo-com' },
  { name: 'payment-cards-money-svgrepo-com', icon: 'svgo-avatar-payment-cards-money-svgrepo-com' },
  { name: 'piggy-bank-svgrepo-com', icon: 'svgo-avatar-piggy-bank-svgrepo-com' },
  { name: 'safebox-bank-svgrepo-com', icon: 'svgo-avatar-safebox-bank-svgrepo-com' },
  { name: 'tag-price-label-svgrepo-com', icon: 'svgo-avatar-tag-price-label-svgrepo-com' },
  { name: 'wallet-money-business-svgrepo-com', icon: 'svgo-avatar-wallet-money-business-svgrepo-com' },
  { name: 'wallet-svgrepo-com-2', icon: 'svgo-avatar-wallet-svgrepo-com-2' },
  { name: 'wallet-svgrepo-com', icon: 'svgo-avatar-wallet-svgrepo-com' },
]

export const custom = {
  exchange: 'svgo-custom-exchange',
}
